server {
    listen 80;
    listen [::]:80;
    server_name insight.bantos.cloud;

    root /var/www/bantos.cloud/bantos-datacenter/insight-client/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
