// Automatically generated from Response_Codes.xlsx
const RESPONSE_CODES = {
  "10": "Partial Approval",
  "11": "Approved (VIP)",
  "12": "Invalid transaction",
  "13": "Invalid amount",
  "14": "Invalid card number (no such number)",
  "15": "No such issuer",
  "17": "Customer cancellation",
  "22": "Suspected malfunction",
  "30": "Format error",
  "31": "Bank not supported by switch",
  "33": "Expired card",
  "34": "Suspected fraud",
  "35": "Card acceptor contact acquirer",
  "36": "Restricted card",
  "37": "Card acceptor call acquirer security",
  "38": "Allowable PIN tries exceeded",
  "39": "No credit account",
  "40": "Requested Function not supported",
  "41": "Lost card",
  "43": "Stolen card, pick-up",
  "51": "Not sufficient funds",
  "54": "Expired card",
  "55": "Incorrect personal identification number",
  "56": "No card record",
  "57": "Transaction not permitted to cardholder",
  "58": "Transaction not permitted to terminal",
  "61": "Exceeds withdrawal amount limit",
  "62": "Restricted card",
  "64": "Original amount incorrect",
  "65": "Exceeds withdrawal count limit OR Identity Check",
  "68": "Response received too late",
  "75": "Allowable number of PIN tries exceeded",
  "76": "Approved country club",
  "77": "Approved pending identification (sign paper draft)",
  "78": "Approved blind",
  "79": "Approved administrative transaction",
  "80": "Approved national negative file hit OK",
  "81": "Approved commercial",
  "82": "No security module",
  "83": "No accounts",
  "84": "No PBF",
  "85": "PBF update error",
  "86": "Invalid authorization type",
  "87": "Bad Track Data",
  "88": "PTLF error",
  "89": "Invalid route service",
  "90": "Cutoff is in process, a switch is ending business for a day and starting the next",
  "91": "Issuer or switch is inoperative",
  "92": "Financial institution or intermediate network facility cannot be found for routing, Decline",
  "93": "Error. Unable to process",
  "94": "Duplicate transaction",
  "95": "Reconcile error",
  "96": "System malfunction",
  "97": "Error. Unable to process",
  "98": "Error. Unable to process",
  "99": "Payment Deferred Parameter Inv",
  "00": "Approved or completed successfully",
  "01": "Refer to card issuer. Place call",
  "02": "Refer to special conditions for card issuer. Issue call",
  "03": "Invalid merchant",
  "04": "Pick-up card",
  "05": "Do not honor, decline",
  "06": "Error",
  "07": "Pick-up card, special condition",
  "08": "Honor with identification",
  "09": "Request in progress",
  "N0": "Unable to authorize",
  "N1": "Invalid PAN length",
  "N2": "Preauthorization full",
  "N3": "Maximum online refund reached",
  "N4": "Maximum offline refund reached",
  "N5": "Maximum credit per refund",
  "N6": "Maximum refund credit reached",
  "N7": "Customer selected negative file reason",
  "N8": "Over floor limit",
  "N9": "Maximum number refund credits",
  "O0": "Referral file full",
  "O1": "NEG file problem",
  "O2": "Advance less than minimum",
  "O3": "Delinquent",
  "O4": "Over limit table",
  "O6": "Mod 10 check",
  "O7": "Force post",
  "O8": "Bad PBF",
  "O9": "NEG file problem",
  "P0": "CAF problem",
  "P1": "Over daily limit",
  "P2": "CAPF not found",
  "P3": "Advance less than minimum",
  "P4": "Number of times used",
  "P5": "Delinquent",
  "P6": "Over limit table",
  "P7": "Advance less than minimum",
  "P8": "Administrative card needed",
  "P9": "Enter lesser amount",
  "Q0": "Invalid transaction date",
  "Q1": "Invalid expiration date",
  "Q2": "Invalid transaction code",
  "Q3": "Advance less than minimum",
  "Q4": "Number of times used",
  "Q5": "Delinquent",
  "Q6": "Over limit table",
  "Q7": "Amount over maximum",
  "Q8": "Administrative card not found",
  "Q9": "Administrative card not allowed",
  "R0": "Approved administrative request performed in window",
  "R1": "Approved administrative request performed out of window",
  "R2": "Approved administrative request performed anytime",
  "R3": "Chargeback, customer file updated",
  "R4": "Chargeback, customer file updated, acquirer not found",
  "R5": "Chargeback, incorrect prefix number",
  "R6": "Chargeback, incorrect response code or CPF configuration",
  "R7": "Administrative transactions not supported",
  "R8": "Card on national negative file",
  "S4": "PTLF full",
  "S5": "Chargeback approved, customer file not updated",
  "S6": "Chargeback approved, customer file not updated, acquirer not found",
  "S7": "Chargeback accepted, incorrect destination",
  "S8": "ADMN file problem",
  "T1": "Invalid credit card advance amount",
  "T2": "Invalid transaction date",
  "T3": "Card not supported",
  "T4": "Amount over maximum",
  "T5": "CAF status = 0 or 9",
  "T6": "Bad UAF",
  "T7": "Cash back exceeds daily limit",
  "1A": "Additional customer authentication required",
  "U0": "Cryptogram verification failure decline",
  "U1": "MAC failure",
  "U2": "KMAC synchronization error",
  "U3": "Message replay error",
  "U4": "Invalid MAC",
  "U5": "KME synchronization error",
  "U6": "TVR decline",
  "U7": "Reason online code decline",
  "U8": "Fallback decline",
  "V0": "Cryptogram verification failure referral",
  "V1": "CVR referral",
  "V2": "TVR referral",
  "V3": "Reason online code referral",
  "V4": "Fallback referral",
  "V7": "Cryptogram verification failure capture",
  "V8": "CVR capture",
  "V9": "TVR capture",
  "R9": "Destination not available",
  "S0": "Suspect reversal",
  "S1": "Suspicious reversal override",
  "S2": "Misdispense reversal override",
  "S3": "PLUS add cash withdrawal or advance",
  "T9": "Duplicated Transaction"
};

export const getResponseCodeName = (code) => {
    return RESPONSE_CODES[code] || 'Unknown error code';
};
