CREATE TABLE IF NOT EXISTS tenant_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tenant_id VARCHAR(50) NOT NULL,
  whitelabel_name VARCHAR(255) DEFAULT NULL,
  whitelabel_logo LONGTEXT DEFAULT NULL,
  smtp_host VARCHAR(255) DEFAULT NULL,
  smtp_port VARCHAR(10) DEFAULT NULL,
  smtp_user VARCHAR(255) DEFAULT NULL,
  smtp_pass VARCHAR(255) DEFAULT NULL,
  smtp_secure BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_tenant (tenant_id)
);
